version: '3.7'

services:
  nudges:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 80 --reload
    volumes:
      - ./:/app
    ports:
      - 80:80
    depends_on:
      - db
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: username
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: nudges
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3306:3306  # Expone el puerto para conexiones locales
    expose:
      - 3306

volumes:
  mysql_data: